# Generated by Django 4.0.5 on 2022-06-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=100)),
                ('Data', models.DateField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Imagem', models.FileField(upload_to='img_aluga/%d/%m/%Y')),
                ('Noites', models.IntegerField(blank=True)),
                ('Nome', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
