# Generated by Django 4.0.5 on 2022-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_alugar_vago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alugar',
            name='Data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='alugar',
            name='Valor',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
