# Generated by Django 4.0.5 on 2022-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0004_alter_alugar_data_alter_alugar_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alugar_quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('Data_de_entrada', models.DateField(blank=True)),
                ('Data_de_saida', models.DateField(blank=True)),
                ('Caracter', models.TextField(max_length=200)),
                ('Camas', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Vago', models.BooleanField()),
                ('Preco', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Imagem', models.FileField(upload_to='alug_quart/%d/%m/%Y')),
            ],
        ),
    ]
