# Generated by Django 4.0.5 on 2022-06-08 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heart', '0006_alter_alugar_quarto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartos_para_alugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=100)),
                ('Data_de_entrada', models.DateField(blank=True)),
                ('Data_de_saida', models.DateField(blank=True)),
                ('Caracter', models.TextField(max_length=200)),
                ('Camas', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Vago', models.BooleanField()),
                ('Preco', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Imagem', models.FileField(upload_to='alug_quart/%d/%m/%Y')),
            ],
        ),
        migrations.AlterField(
            model_name='alugar_quarto',
            name='Nome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
